### ISSUE TITLE
RapidSVN

### ISSUE THREAD

**Issue by satiutni** [seb4stien/freeplane-collaborative-addon#19]
I notice you have implemented SVN utilising the TortoiseSVN client, although my school-years French makes my understanding incomplete.
With the advent of Freeplane for the Mac I was wondering if it might be possible to implement something like RapidSVN to allow cross-platform collaboration. I am not Java competent so my ability to contribute is probably nil. My reason for asking is that I am involved in an open source design collaborative called OpenIDEO (www.openideo.com) and I believe collaborative mind-mapping would be of significant use to that community.
Cheers Paul

**Comment by seb4stien** [comment]
The add-on only needs a command line svn binary.
It seems that svn is shipped with Mac Os X, so you have nothing to install to use the add-on under Mac.
Just configure the path to your svn binary in the Preferences and it should work.

Let me know if it works correctly.

**Comment by satiutni** [comment]
Thank you for this advice, As I only have Windows XP I will get my son to check through his Mac Os X (if he is willing) and let you know. I was hoping to submit Collaborative Freeplane as an external tool to the community on the OpenIDEO crowdsourcing platform.
