### ISSUE TITLE
format de date non valide

### ISSUE THREAD

**Issue by flarrive** [seb4stien/freeplane-collaborative-addon#23]
ubuntu 12.04 64 bits, language : french
freeplane 1.3.11
git 1.7.9.5

when configuring the addon (git path : /usr/bin/git) I've got the following message :
Le format de date n'est pas valide (The date format is not valid)
Le format de date/heure n'est pas valide (The date/hour format of  is not valid)
Le format de nombre n'est pas valide (The  format of number is not valid)
Merci de modifier les préférences (Thank you for modifying the preferences)

What should I do ?

**Comment by seb4stien** [comment]
Hi,

I couldn't reproduce the problem. Was it a fresh install of freeplane or an upgrade from 1.2 ?
If it was an upgrade, you could try to remove and reinstall the add-on directly under 1.3.

Tell me if it helps,
Sébastien

**Comment by flarrive** [comment]
I've just try to remove and reinstall, but i've got the same message when configuring the add-on.

Franck

**Comment by xverges** [comment]
I'm also getting a similar message. Fresh install, both of free plane and the add-on

![invalid-date-format](https://cloud.githubusercontent.com/assets/460418/3655613/028e1302-117c-11e4-9094-0c89656c9637.png)

**Comment by xverges** [comment]
After restarting, editing directly the `preferences to set my git.exe path, things worked

**Comment by flarrive** [comment]
configuring the add-on with :
Outils->Add-ons->Outils collaboratifs->Configurer
(Tools->Add-ons->Collaborative Tools->Configure),
I've got the message.

configuring the add-on with :
Outils->Preferences->Formules & Scripts
(Tools->Preferences->Plugins)
I can set my git path without any message and all works fine.

Franck

**Comment by freeman42x** [comment]
I had the same issue (when changing from Tools->Add-ons->Collaborative Tools->Configure) and what worked for me was the same fix mentioned by @flarrive change it from Tools->Preferences->Plugins instead.

**Comment by denyeo** [comment]
Same problem here. @flarrive's solution worked for me as well.

**Comment by wilsonch0** [comment]
Ditto. @flarrive 's solution worked for me.

**Comment by seb4stien** [comment]
See fix in #22
